spring.profiles.active: local
---
spring:
  profiles: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emitter?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
---

spring:
  profiles: JiradaW
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.4.56.34:3306/homework?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: 1234
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
    security:
  basic:
    enabled: false
    

